### ISSUE TITLE
There should be a delay when authentication fails

### ISSUE THREAD

**Issue by lprimak** [stormpath/idsite-src#11]
When user types in wrong email / password, there should be a delay before printing an error message.
This way, an attacker that tries a dictionary attach won't be able to rapid-fire authentication attempts,
and thus will not be able to succeed in a dictionary attack or put high load on the server

**Comment by robertjd** [comment]
A delay would slow down a dictionary attack, but not prevent it.  Using something like Captcha would be a better solution.

**Comment by lprimak** [comment]
Capcha works but it's a more complicated solution. Can we start with a delay first?

**Comment by lprimak** [comment]
I just discovered that the ID site fails with "unknown XHR error" after 10 attempts.  This error is too cryptic.  It should be changed to "too many authentication failures" or something like that.

**Comment by lprimak** [comment]
Patch to introduce a delay to the ID site: 
https://github.com/robertjd/idsite-src/commit/45a032f52b4b813eaa345daec7aabef7766e9271
