### ISSUE TITLE
add Github Login functionality

### ISSUE THREAD

**Issue by dogeared** [stormpath/idsite-src#119]
Looks like `$scope.githubLogin` function is required in `app/scripts/controllers/login.js` at a minimum.

**Comment by robertjd** [comment]
Github does not provide a popup-based login flow, they only provide a page-based flow.  ID Site is purely a front-end application, so the user would not be able to come back to ID Site after they are redirected back from Github after authentication.  They would need to be sent back to the customer's server infrastructure, where the Github authentication token would need to be received and used to resolve the account.  Thus, the modification to ID Site would simply be to render the button that begins the redirect flow for Github.
