### ISSUE TITLE
Add links to directly log in via google / facebook

### ISSUE THREAD

**Issue by lprimak** [stormpath/idsite-src#12]
Right now, the id site supports direct links to "forgot password" or "create new account"
via #/register or #/forgot 

I would like to add #/facebook or #/google links so the social logins can be accessed via external links and without users having to click twice.

**Comment by robertjd** [comment]
This is a great idea, thanks for the feedback!

**Comment by lprimak** [comment]
Does this mean this is done?

**Comment by robertjd** [comment]
Not yet :) we'll update this issue when we implement this.

**Comment by lprimak** [comment]
Any update on this issue?  We are very much looking forward to this feature.
Thank you

**Comment by lprimak** [comment]
Still waiting on this... thanks!

**Comment by lprimak** [comment]
I guess this got orphaned
