### ISSUE TITLE
Cryptic error message when user tries to login > 10 times

### ISSUE THREAD

**Issue by lprimak** [stormpath/idsite-src#14]
When user tries incorrectly to login more than 10 times,
"unknown XHR error" is displayed.  This should be something more user friendly, such as "too many incorrect login attempts" or something like that

**Comment by robertjd** [comment]
Thanks for the report.  This may have been an artifact of #2 

I can't reproduce this error.  Are you still experiencing this problem?

**Comment by lprimak** [comment]
I think you are right.  No longer able to reproduce this as well
