### ISSUE TITLE
"Unknown XHR Error" when administrator is logged in to stormpath.com

### ISSUE THREAD

**Issue by omgitstom** [stormpath/idsite-src#2]
Developers that are logged into stormpath.com administration console when doing actions on ID Site (such login / signup / social / etc) will receive an Unknown XHR Error.  Logging out of the Stormpath.com or using an incognito window is a temporary solution.

**Comment by skolsuper** [comment]
+1, this is pretty annoying

**Comment by scan5415** [comment]
+1

**Comment by omgitstom** [comment]
Just wanted to update you folks. In the next few weeks, we will be sunsetting the old admin console, which is where the ID Site configuration currently resides.  This configuration will be moved to the new admin console and this issue should be resolved (we will do some additional testing to make sure).  In the meantime as a workaround, and what I'm currently doing as well, is running ID Site in an incognito / private browsing window. Thanks!

**Comment by ikhemissi** [comment]
+1
(and thanks for the tip)

**Comment by moravcik** [comment]
I am afraid this issue is addressing also the new admin console. I am always getting "Unknown XHR error" when administering the ID site using new ui.

**Comment by bloo** [comment]
Likewise - pretty confusing.

**Comment by robertjd** [comment]
This has been resolved by #54 (Release 0.2.2).  Our default production ID Site is now using that release.
