### ISSUE TITLE
jwtBody iat is an invalid value

### ISSUE THREAD

**Issue by omgitstom** [stormpath/idsite-src#3]
When using the ID Site, it is possible that the application server that is hosting the SDK will have a different time than the ID Site. Since we use an issued-at-time to calculate a valid JWT. It is possible when the application server isn't well managed that the time calculation can be off and the developer can run into:
{"status":400,"code":2002,"message":"jwtBody iat is an invalid value.","developerMessage":"jwtBody iat is an invalid value.","moreInfo":"http://docs.stormpath.com/errors/2002"}

Update: Stormpath has a 60 sec skew window when calculating iat.  This is a large window.  If your applications are still receiving this error, please make sure your application server and using a ntp server to sync time.

**Comment by schwer** [comment]
Any progress on this? I'm fairly certain that the solution will involve setting a clock-skew 'window' wherein iat, expiration times can accommodate some clock skew.

**Comment by robbydooo** [comment]
I am getting this error, have we found a solution to this? Looks like this has been open for over a year.

**Comment by lprimak** [comment]
I agree.  There are other many (around 10) other issues that I opened support tickets for that haven't been looked at for over a year.

I understand Stormpath debs are busy making new features, but I think there should be some time devoted to fix customer bugs.

Thank you!

**Comment by omgitstom** [comment]
@schwer : I'm going to update this issue, we have made a few changes to the backend and I am going to consider this issue resolved.   Stormpath is keeping the iat in the JWT and will still be validating it.  We updated the skew window from 10 seconds to 60 seconds which gives a larger skew window before errors occur.  Additionally, we recommend that customers use a ntp server to keep their server clocks up to date.

**Comment by omgitstom** [comment]
@lprimak : I manage Product at Stormpath.  We have actually resolved and added a lot of functionality to ID Site over the past year.  We like to keep you updated if feature requests will be added or not.   I see that no one on the team has replied to the rest of the cases that were logged on the ID Site and I want to reply accordingly on those issues. Thanks, and feel free to reach out to me directly if you would like to discuss this further.
