### ISSUE TITLE
api.stormpath.com not responding with Access-Control-Allow-Origin set for POST part of loginAttempts

### ISSUE THREAD

**Issue by george-hawkins-aa** [stormpath/idsite-src#30]
I'm working through the [ID site](https://docs.stormpath.com/java/spring-boot-web/idsite.html) section of the Spring Boot Stormpath documentation.

I'm now trying to login via the ID site but this fails - in the Chrome console I see:
```
XMLHttpRequest cannot load https://api.stormpath.com/v1/applications/XYZ/loginAttempts.
No 'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'https://tenant-name.id.stormpath.io' is therefore not allowed access.
```
And if I look at what's happening I see two `loginAttempts` requests - the first with request method `OPTIONS` that succeeds as the response includes:
```
Access-Control-Allow-Origin:https://tenant-name.id.stormpath.io
```
The second `loginAttempts` request has request method `POST` and this one fails - it gets a 200 response but without any `Access-Control` headers so Chrome rejects it.

I presume these `loginAttempts` requests are what I see in [`client.js`](https://github.com/stormpath/stormpath.js/blob/b3e48d7/lib/client.js#L85) in the stormpath.js repo - I just see the minified form when interacting with the ID site so it's not super clear what's going on :smile:

I'm running Chrome version 45 with user agent value `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36`.

Note: I replaced my actual tenant name with `tenant-name` and my application ID with `XYZ` - but I guess that's obvious.

**Comment by robertjd** [comment]
Hello George!  Can you take a look at #2 and let me know if it describes your problem?

**Comment by george-hawkins-aa** [comment]
Yes it does.

My administration access had timed out and I'd closed the relevant tab in my browser, but I still experienced the issue. Once I logged back in and explicitly logged out (rather than letting things just time out) it all worked.

Hmm... I was so pleased with myself for finding what seemed to be going on in the Chrome developer tools - but I should have just invested my time properly looking at the earlier issues.

Thanks :smile:

**Comment by robertjd** [comment]
Happy to help!  Debugging CORS issues in Chrome is an adventure that we all get to have at some point :)
