### ISSUE TITLE
Can't develop using grunt serve

### ISSUE THREAD

**Issue by rainabba** [stormpath/idsite-src#6]
When I do, all routes display the following. If I provide a token, it fails for expected reasons (token expired and such):

Sorry, there is a problem. The error is:

jwt not found as url query parameter

Please use your browser's back button to return to the previous page, then try again.

**Comment by moravcik** [comment]
same for me, I don't know how to test it

**Comment by lhazlewood** [comment]
ID Site is not currently accessible directly. That is, you cannot 'start' there. You must start in a web application that uses Stormpath and then be redirected to ID Site.

**Comment by robertjd** [comment]
Hey @moravcik It is possible to have a local development worklow for ID site, but as @lhazlewood mentions you do need to redirect the user to the app that is running via `grunt serve` - and they need to land there with an appropriate token.  We refer to this as the "service provider initiated flow"

I have a small project which I for just this, it renders a login button starts the SP initiated flow:

https://github.com/robertjd/fakesp/

The documentation may be a bit out of date, so please feel free to ask questions if you get suck - either on Github or via support@stormpath.com

Hope this helps!

**Comment by robertjd** [comment]
The information in my last comment has been incorporated into the Readme, please use the Readme for information on setting up a local development environment for ID Site.
