### ISSUE TITLE
Fresh clone isn't working for actual idsite

### ISSUE THREAD

**Issue by rainabba** [stormpath/idsite-src#8]
I did a 'git clone' of this repo, 'npm install' (though that had an issue: https://github.com/stormpath/idsite-src/issues/7) then 'bower install'. Just pushing that and setting my idsite to use it, I end up with the following on my production site. Since 'grunt build' doesn't appear to change any tracked files, I'm guessing that issue #7 would have no impact on this and it looks to me like a file isn't getting synced to the CDN (I did try the sync button on the idsite dash a few times), but that's just my guess.

**404 Not Found**

*Code: NoSuchKey
*Message: The specified key does not exist.
*Key: index.html
*RequestId: FCA37DBAF69F3E7D
*HostId: *rt2oWPnaDAyjKQ2JS4wRE0DrDIr5LZ5zTuloDxzUp8T7Z+ccEMgrBwd6qJGhvcmPnakcrieeuh4=

**An Error Occurred While Attempting to Retrieve a Custom Error Document**

*Code: NoSuchKey
*Message: The specified key does not exist.
*Key: error.html

**Comment by robertjd** [comment]
This was a momentary problem with our caching layer that serves ID Site repositories.  This should no longer be a problem.
